-- MySQL Script generated by MySQL Workbench
-- Wed Jul  4 20:25:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso` DEFAULT CHARACTER SET utf8 ;
USE `curso` ;

-- -----------------------------------------------------
-- Table `curso`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `valor_hora` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `conteudo` LONGTEXT NULL,
  `carga_horaria` DOUBLE NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`aula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fkDisciplina` INT NOT NULL,
  `fkProfessor` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fkDisciplina_idx` (`fkDisciplina` ASC),
  INDEX `fkProfessor_idx` (`fkProfessor` ASC),
  CONSTRAINT `fkDisciplina`
    FOREIGN KEY (`fkDisciplina`)
    REFERENCES `curso`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProfessor`
    FOREIGN KEY (`fkProfessor`)
    REFERENCES `curso`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`aula-aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`aula-aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fkAula` INT NOT NULL,
  `fkAluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkAula_idx` (`fkAula` ASC),
  INDEX `fkAluno_idx` (`fkAluno` ASC),
  CONSTRAINT `fkAula`
    FOREIGN KEY (`fkAula`)
    REFERENCES `curso`.`aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAluno`
    FOREIGN KEY (`fkAluno`)
    REFERENCES `curso`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`professor-disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`professor-disciplinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fkProfessor` INT NULL,
  `fkDisciplina` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkProfessor2_idx` (`fkProfessor` ASC),
  INDEX `fkDisciplina2_idx` (`fkDisciplina` ASC),
  CONSTRAINT `fkProfessor2`
    FOREIGN KEY (`fkProfessor`)
    REFERENCES `curso`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDisciplina2`
    FOREIGN KEY (`fkDisciplina`)
    REFERENCES `curso`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
